library(gris)
library(rgdal)
cmu <- gris(readOGR("data-raw/CMU.mif", "CMU"))
save(cmu, file = "data/cmu.rdata", compress = "xz")

#' CMU banner
#'
#' A gris dataset of the example CMU banner used by Shewchuk to illustrate the features of Triangle.
#'
#' @format A gris object composed of five line objects.
#' @source This was generated by tracing the image used on the Triangle site
#' in Manifold GIS, then exporting that to MapInfo file (.mif) and reading it in with rgdal. \url{https://www.cs.cmu.edu/~quake/triangle.demo.html}
#' library(rgdal); library(gris);  cmu <- gris(readOGR("CMU.mif", "CMU"))
#' @note This data set has a "background" polygon which intersects the internal rings - it's not a "partition of the plane".
"cmu"



