---
title: "Examples for gris"
author: "Michael Sumner"
date: "2015-05-19"
output: html_document
---

## Examples

Build objects from other packages. 

```{r}
library(gris)
library(maptools)
data(wrld_simpl)
dat <- bld(wrld_simpl)
dat1 <- sbs(dat, filter(dat$o, NAME %in% c("Australia", "Indonesia")))
pl(dat1$v)
```

Triangulate with CGAL via [cgalgris](https://github.com/mdsumner/cgalgris). 

```{r,eval=FALSE}
library(cgalgris)
## Delaunay triangulation (unconstrained)
dat1$vi <- tri_xy(dat1$v$x, dat1$v$y) + 1  ## plus 1 for R indexing

## centroids of triangles
centr <- data_frame(x = dat1$v$x[dat1$vi], y = dat1$v$y[dat1$vi], t = rep(seq(length(dat1$vi)/3), each = 3)) %>% group_by(t) %>% summarize(x = mean(x), y = mean(y)) %>% select(x, y, t)
points(centr[, c("x", "y")])  
x1 <- dat1$v %>% mutate(mg = .br0) %>%  group_by(mg) %>% do(rbind(., NA_real_))
inside <- which(point.in.polygon(centr$x, centr$y, x1$x, x1$y) == 1)
## plot all triangles
plot(dat1$v$x, dat1$v$y, type = "n")
col <- sample(rainbow(10), 1)
apply(matrix(dat1$vi, ncol = 3, byrow = TRUE), 1, function(x) polypath(cbind(dat1$v$x[x], dat1$v$y[x]), col = col))
## overplot only those that are internal to the polygons (not exact since triangulation is unconstrained)
col <- sample(rainbow(10), 1)
apply(matrix(dat1$vi, ncol = 3, byrow = TRUE)[inside, ], 1, function(x) polypath(cbind(dat1$v$x[x], dat1$v$y[x]), col = col, border = NA))

```

Build up the objects from scratch. 

```{r}
library(gris)

## one object, two branches
v1 <- data_frame(x = c(0, 1, 0.5), y = c(0, 0, 1), .br0 = 1, .ob0 = 1)
v2 <- data_frame(x = c(1, 1, 0.5), y = c(0, 1, 1), .br0 = 2, .ob0 = 1)

## another object two branches
v3 <- v1 %>% mutate(x = x + 2, .br0 = 4, .ob0 = 2)
v4 <- v2 %>% mutate(x = x + 2, .br0 = 5, .ob0 = 2)
## third branch in first  object
v0 <- data_frame(x = c(0.1, 0.4, 0.2), y = c(0.05, 0.05, 0.12), .br0 = 3, .ob0 = 1)
v <- bind_rows(v1,  v2, v0,  v3, v4) %>% mutate(id = seq(n()))

## plot with two colours
pl(v, col = c("lightgrey", "darkgrey"))

## build a composite with data attributes on the individual objects
b <- v %>% distinct(.br0) %>% select(.br0, .ob0)
o <- b %>% distinct(.ob0) %>% mutate(id = .ob0) %>% select(id)
o$Name <- c("p", "q")
##v <- v %>% select(-.ob0)

x <- list(v = v, b = b, o = o)

## subset by name
dq <- sbs(x, filter(x$o, Name == "q"))
pl(dq$v, col = "green")
```
