---
title: "Untitled"
author: "Michael Sumner"
date: "29 December 2015"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Image textures

```{r plot3d_texture, webgl = TRUE, rgl.newwindow = TRUE}
## marmap has some topography
library(marmap)
data("hawaii", package = "marmap")
r <- marmap::as.raster(hawaii)
## but is otherwise undesirable so we unload it
unloadNamespace("marmap")
library(dismo)
gm <- gmap(r, type = "satellite", scale = 2)
#gm <- raster()
## this is our texture
paletteim2RGB <- function(x) {
  ct <-  col2rgb(x@legend@colortable[values(x) + 1])

  setValues(brick(x, x, x), t(ct))
}
library(rgdal)
texture <- writeGDAL(as(paletteim2RGB(gm), "SpatialGridDataFrame"), "texture.png", drivername = "PNG", type = "Byte")

library(gris)
library(rgl)
library(rglwidget)
b <- bgl(r, r)
tcoords <- xyFromCell(setExtent(gm, c(0, 1, 0, 1)), cellFromXY(gm, project(t(b$vb[1:2, ]), projection(gm))))
aspect3d(1, 1, 0.0001)
#shade3d(b, col = "white", texture= texture, texcoords = tcoords[b$ib, ])

quads3d(t(b$vb[1:3, b$ib]), col = "white", texture= texture, texcoords = tcoords[b$ib, ])
subid <- currentSubscene3d()
rglwidget(elementId="plot3d_texture")
rgl.close()
```