#' gris: A flexible geometry data model for R.
#'
#' The gris package provides a flexible basis for spatial data in R.
#'
#' @section gris functions:
#' plotting
#' subsetting
#' building
#' ... transforming
#' ...
#' @name gris
#' @docType package
NULL


#' CMU banner
#' 
#' A gris dataset of the example CMU banner used by Shewchuk to illustrate the features of Triangle. 
#' 
#' @format A gris object composed of five line objects. 
#' @source This was generated by tracing the image used on the Triangle site
#' in Manifold GIS, then exporting that to MapInfo file (.mif) and reading it in with rgdal. \url{https://www.cs.cmu.edu/~quake/triangle.demo.html}
#' library(rgdal); library(gris);  cmu <- gris(readOGR("CMU.mif", "CMU"))
#' @note This data set has a "background" polygon which intersects the internal rings - it's not a "partition of the plane".
"cmu"

#' Template quad 3d object
#' 
#' 
#' @format see rgl oh3d
"q3d"

#' Template triangle 3d object
#' 
#' 
#' @format see rgl tetrahedron3d
"t3d"
